{{- if eq .Values.crdType "TVOControlPlane" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triliovault-datamover-api
  labels:
    application: triliovault
    component: datamover-api
    owner: triliovault-datamover
    service: triliovault-datamover
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "100"
spec:
  replicas: {{ .Values.pod.replicas.triliovault_datamover_api }}
  selector:
    matchLabels:
      application: triliovault
      component: datamover-api
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        application: triliovault
        component: datamover-api
        owner: triliovault-datamover
        service: triliovault-datamover
    spec:
      serviceAccountName: triliovault-datamover-api
      securityContext:
        runAsUser: {{ .Values.pod.security_context.triliovault.container.triliovault_datamover_api.runAsUser }}
        fsGroup: {{ .Values.pod.security_context.triliovault.container.triliovault_datamover_api.runAsGroup }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: application
                    operator: In
                    values:
                    - triliovault
                  - key: component
                    operator: In
                    values:
                    - datamover-api
              topologyKey: kubernetes.io/hostname
            weight: 10
      nodeSelector:
        trilio-control-plane: enabled
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: triliovault-datamover-api-init
          image: {{ .Values.images.triliovault_datamover_api }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - /tmp/triliovault-datamover-api-init.sh
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          terminationMessagePath: /var/log/termination-log
          volumeMounts:
            - name: triliovault-datamover-api-bin
              mountPath: /tmp/triliovault-datamover-api-init.sh
              subPath: triliovault-datamover-api-init.sh
            - name: triliovault-datamover-api-bin
              mountPath: /tmp/triliovault-cloudrc
              subPath: triliovault-cloudrc
            - name: pod-shared-triliovault-datamover-api
              mountPath: /tmp/pod-shared-triliovault-datamover-api
            - name: triliovault-datamover-api-etc
              mountPath: /etc/pki/tls/certs/openstack-ca-cert.pem
              subPath: ca-cert.pem
              readOnly: true
      containers:
        - name: triliovault-datamover-api
          image: {{ .Values.images.triliovault_datamover_api }}
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: false
          command:
            - /bin/bash
            - -c
            - /tmp/triliovault-datamover-api.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /tmp/triliovault-datamover-api.sh
                  - stop
          ports:
            - name: dm-api
              containerPort: 8783
          readinessProbe:
            tcpSocket:
              port: 8783
          livenessProbe:
            tcpSocket:
              port: 8783
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: triliovault-datamover-api-etc
              mountPath: /etc/triliovault-datamover/triliovault-datamover-api.conf
              subPath: triliovault-datamover-api.conf
              readOnly: true
            - name: triliovault-datamover-api-etc
              mountPath: /etc/triliovault-datamover/datamover_api_logging.conf
              subPath: datamover_api_logging.conf
              readOnly: true
            - name: triliovault-datamover-api-etc
              mountPath: /etc/httpd/conf.d/triliovault_datamover_httpd.conf
              subPath: triliovault_datamover_httpd.conf
              readOnly: true  
            - name: triliovault-datamover-api-etc
              mountPath: /etc/pki/tls/certs/openstack-ca-cert.pem
              subPath: ca-cert.pem
              readOnly: true
            - name: triliovault-datamover-api-bin
              mountPath: /tmp/triliovault-datamover-api.sh
              subPath: triliovault-datamover-api.sh
            - name: pod-shared-triliovault-datamover-api
              mountPath: /tmp/pod-shared-triliovault-datamover-api
            - name: trilio-logs
              mountPath: /var/log/triliovault
            - mountPath: /etc/pki/tls/certs/internal.crt
              name: internal-tls-certs
              readOnly: true
              subPath: tls.crt
            - mountPath: /etc/pki/tls/private/internal.key
              name: internal-tls-certs
              readOnly: true
              subPath: tls.key
            - mountPath: /etc/pki/tls/certs/public.crt
              name: public-tls-certs
              readOnly: true
              subPath: tls.crt
            - mountPath: /etc/pki/tls/private/public.key
              name: public-tls-certs
              readOnly: true
              subPath: tls.key
            - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
              name: combined-ca-bundle
              readOnly: true
              subPath: tls-ca-bundle.pem
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: triliovault-datamover-api-etc
          secret:
            secretName: triliovault-datamover-api-etc
            defaultMode: 0444
        - name: triliovault-datamover-api-bin
          configMap:
            name: triliovault-datamover-api-bin
            defaultMode: 0555
        - name: trilio-logs
          emptyDir: {}
        - name: pod-shared-triliovault-datamover-api
          emptyDir: {}
        - name: public-tls-certs
          secret:
            secretName: cert-triliovault-datamover-public-svc
            defaultMode: 0640
        - name: internal-tls-certs
          secret:
            secretName: cert-triliovault-datamover-internal-svc
            defaultMode: 0640
        - name: combined-ca-bundle
          secret:
            defaultMode: 292
            secretName: combined-ca-bundle
{{- end }}