{{- if and (eq .Values.crdType "TVOBackupTarget") (eq .Values.triliovault_backup_target.backup_target_type "nfs") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: job-triliovault-nfs-mount-{{ .Values.triliovault_backup_target.backup_target_name | lower | replace "_" "-" }}
  labels:
    application: triliovault
    component: wlm-nfs-mount
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-4"
spec:
  backoffLimit: 1000
  template:
    metadata:
      labels:
        application: triliovault
        component: wlm-nfs-mount
    spec:
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      serviceAccountName: triliovault-wlm
      restartPolicy: OnFailure
      nodeSelector:
        trilio-control-plane: enabled
      containers:
        - name: "wlm-nfs-mount"
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: {{ .Values.common.nova_user_id }}
          image: {{ .Values.images.triliovault_wlm_api }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - /tmp/triliovault-nfs-mount.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: triliovault-wlm-bin
              mountPath: /tmp/triliovault-nfs-mount.sh
              subPath: triliovault-nfs-mount.sh
            - name: trilio-mounts
              mountPath: {{ .Values.common.vault_data_dir }}
              mountPropagation: Bidirectional
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: triliovault-wlm-bin
          configMap:
            name: triliovault-wlm-bin-single-bt-{{ .Values.triliovault_backup_target.backup_target_name | lower | replace "_" "-" }}
            defaultMode: 0555
        - name: trilio-mounts
          hostPath:
            path: {{ .Values.common.vault_data_dir }}
            type: DirectoryOrCreate
{{- end }}
