apiVersion: tvo.trilio.io/v1
kind: TVOBackupTarget
metadata:
  name: tvobackuptarget-s3-bt4
spec:
  # Default values copied from <project_dir>/helm-charts/tvo-chart/values.yaml
  crdType: "TVOBackupTarget"
  images:
    triliovault_object_store: "docker.io/trilio/trilio-wlm:6.0.24-dev-maint1-2-rhosp18.0"
  triliovault_backup_target:
    backup_target_name: 'S3_BT4'
    backup_target_type: 's3'
    is_default: False
    s3_type: 'other_s3'
    s3_access_key: ''
    s3_secret_key: ''
    s3_region_name: ''
    s3_bucket: ''
    s3_endpoint_url: ''
    s3_signature_version: 'default'
    s3_auth_version: 'DEFAULT'
    s3_bucket_object_lock_enabled: false
    s3_ssl_enabled: true
    s3_ssl_verify: true
    s3_self_signed_cert: true
    s3_ssl_ca_cert: |
      SSL_CERT_LINE_1
      SSL_CERT_LINE_2
      SSL_CERT_LINE_N

