apiVersion: tvo.trilio.io/v1
kind: TVOBackupTarget
metadata:
  name: tvobackuptarget-nfs-bt5
spec:
  # Default values copied from <project_dir>/helm-charts/tvo-chart/values.yaml
  crdType: "TVOBackupTarget"
  images:
    triliovault_wlm_api: "docker.io/trilio/trilio-wlm:6.0.24-dev-maint1-2-rhosp18.0"
  triliovault_backup_target:
    backup_target_name: 'nfs-BT5'
    backup_target_type: 'nfs'
    is_default: False
    nfs_shares: '192.168.2.30:/nfs/share'
    nfs_options: 'nolock,soft,timeo=600,intr,lookupcache=none,nfsvers=3,retrans=10'
